//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6Recipe
{
    using Models;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class EF6RecipesContext : DbContext
    {
        public EF6RecipesContext()
            : base("name=EF6RecipesContext")
        {
        }
    
        public virtual DbSet<Person> People { get; set; }

        public DbSet<SelfReferenceModel> SelfReferenceModels { get; set; }

        public DbSet<EntityMultipleTablesModel> EntityInMultipleTablesModels { get; set; }



        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<SelfReferenceModel>()               // Configure bidirectional association
                        .HasMany(sr => sr.Children)
                        .WithOptional(sr => sr.ParentModel);

            modelBuilder.Entity<EntityMultipleTablesModel>()
                        .Map(m => { m.Properties(p => new { p.Field1InTable1, p.Field1InTable2 }); m.ToTable("Table1", "Chapter2"); })
                        .Map(m => { m.Properties(p => new { p.Field2InTable1 }); m.ToTable("Table2", "Chapter2"); });

            modelBuilder.Entity<TableInMultipleEntitiesModel1>().ToTable("TableName", "Chapter2");
            modelBuilder.Entity<TableInMultipleEntitiesModel2>().ToTable("TableName", "Chapter2");
        }
    }
}
