//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6Recipe.Contexts
{
    using Models;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class Chapter3Context : DbContext
    {
        public Chapter3Context() : base("name=EF6RecipeContext")
        {
        }

        public DbSet<Associate> Associates { get; set; }
        public DbSet<AssociateSalary> AssociateSalaries { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Associate>().ToTable("Associate");
            modelBuilder.Entity<AssociateSalary>().ToTable("AssociateSalary");

            // Explicilty assign key as primary key in AssociateSalary does not meet
            // Entity Framework default mapping conventions.
            modelBuilder.Entity<AssociateSalary>().HasKey(a => a.SalaryId);

            base.OnModelCreating(modelBuilder);
        }
    }
}
